/**
 * A collection of ingredients.
 * Source: https://zdb.se/z/ingredienser/
 */
export default [
    'salt',
    'olja',
    'svartpeppar',
    'smör',
    'ägg',
    'vitlök',
    'socker',
    'vatten',
    'citron',
    'mjöl',
    'vinäger',
    'gul',
    'mjölk',
    'honung',
    'vispgrädde',
    'potatis',
    'crème',
    'rödlök',
    'lime',
    'persilja',
    'grädde',
    'tomat',
    'gurka',
    'ingefära',
    'basilika',
    'kyckling',
    'morötter',
    'vaniljsocker',
    'bakpulver',
    'vitpeppar',
    'koriander',
    'dill',
    'tomatpuré',
    'timjan',
    'lax',
    'morot',
    'purjolök',
    'parmesanost',
    'soja',
    'florsocker',
    'ris',
    'spiskummin',
    'paprika',
    'grönsaksbuljong',
    'fetaost',
    'avokado',
    'kakao',
    'gräslök',
    'jäst', //p1 end
    'nötfärs',
    'ströbröd',
    'dijonsenap',
    'äpple',
    'broccoli',
    'zucchini',
    'majonnäs',
    'paprikapulver',
    'kanel',
    'pasta',
    'lök',
    'röd paprika',
    'fläsk',
    'gräddfil',
    'oregano',
    'krossade tomater',
    'bacon',
    'champinjon',
    'chilipeppar',
    'salladslök',
    'schalottenlök',
    'curry',
    'lagerblad',
    'mynta',
    'hallon',
    'röd lök',
    'apelsin',
    'vitt vin',
    'choklad',
    'mörk choklad',
    'chiliflakes',
    'rosmarin',
    'spenat',
    'cayennepeppar',
    'yoghurt',
    'kokosmjölk',
    'sambal oelek',
    'körsbärstomater',
    'vitkål',
    'sallad',
    'jordgubbe',
    'senap',
    'potatismjöl',
    'havregryn',
    'ruccola',
    'blåbär',
    'saffran',
    'japansk soja',
    'räkor', //p2 end
];
