/**
 * A collection of sports.
 * Source: https://zdb.se/z/sporter/
 */
export default [
    'Aerobics',
    'Agility',
    'Aikido',
    'Air hockey',
    'Amerikansk fotboll',
    'Airsoft',
    'Armbrytning',
    'Australisk fotboll',
    'Artistisk Gymnastik',
    'Backhoppning',
    'Badminton',
    'Bangolf',
    'Bandy',
    'Baseboll',
    'Basket',
    'Beachhandboll',
    'Beach Soccer',
    'Beachvolleyboll',
    'Biljard',
    'Bilsport',
    'Blindfotboll',
    'Blixtboll',
    'Bodybuilding',
    'Bordshockey',
    'Bordtennis',
    'Boule',
    'Boxning',
    'Brasiliansk jiu-jitsu',
    'Breakdance',
    'Bridge',
    'Brottning',
    'Brännboll',
    'Budo',
    'Bågskytte',
    'Basket',
    'Casting',
    'Capoeira',
    'Capoeira angola',
    'Cheerleading',
    'COSOM floorhockey',
    'Curling',
    'Cricket',
    'Cykelsport',
    'Danssport',
    'Dart',
    'Discgolf',
    'Draghundssport',
    'Dragkamp',
    'Dragracing', //p1 end
    'Elefantpolo',
    'Enduro',
    'E-sport',
    'Extremsport',
    'Fistboll',
    'Flygsport',
    'Forspaddling',
    'Fotboll',
    'Free running',
    'Fridykning',
    'Friidrott',
    'Frisbee',
    'Frisksport',
    'Frågesport',
    'Fäktning',
    'Galoppsport',
    'Gaelisk fotboll',
    'Goalball',
    'Golf',
    'Gymnastik',
    'Handboll',
    'Handikappidrott',
    'Hastighetsåkning på skridskor',
    'Highland Games',
    'Hillclimb',
    'Hockey-Bockey',
    'Rinkbandy',
    'Hopprep',
    'Hundsport',
    'Hurling',
    'Hästpolo',
    'Inlinehockey',
    'Innebandy',
    'IPSC',
    'Ishockey',
    'Isracing',
    'Issegling',
    'Isstock',
    'Jai alai',
    'Judo',
    'Jujutsu',
    'Kampsport',
    'Budo',
    'Karate',
    'Kendo',
    'Taekwondo',
    'Kanadensisk fotboll',
    'Kanotsport',
    'Kanot', //p2 end
    'Karting',
    'Kick-boxning',
    'Kidsvolley',
    'Kiiking',
    'Klättring',
    'Konstsim',
    'Konståkning',
    'Korfball',
    'Korgboll',
    'Kroppsbyggande',
    'Kronum',
    'Kärringkånk',
    'Lacrosse',
    'Landhockey',
    'Le Parkour',
    'Maraton',
    'Minibasket',
    'Mixed martial arts',
    'MMA',
    'Motocross',
    'Motorsport',
    'Mountainbike',
    'Multisport',
    'Netball',
    'Orientering',
    'Mountainbikeorientering',
    'Skidorientering',
    'Precisionsorientering',
    'Padeltennis',
    'Paintball',
    'Parkour',
    'Pelota',
    'Pärk',
    'Ridsport',
    'Rinkbandy',
    'Rinkboll',
    'Roadracing',
    'Rodd',
    'Kyrkbåtsrodd',
    'Tiohuggarrodd',
    'Rodel',
    'Roller Derby',
    'Rugby',
    'Rullskridskohockey',
    'Rytmisk gymnastik',
    'Schack',
    'Segling',
    'Sepak takraw',
    'Shinty', //p3 end
    'Simhopp',
    'Simning',
    'Skateboard',
    'Skaterhockey',
    'Skeleton',
    'Skidsport',
    'Alpin skidsport',
    'Backhoppning',
    'Freestyle',
    'Längdåkning',
    'Nordisk kombination',
    'Rullskidor',
    'Rullskidskytte',
    'Skicross',
    'Skidorientering',
    'Snowboard',
    'Speedski',
    'Telemark',
    'Skidskytte',
    'Skridsko',
    'Skytte',
    'Slamball',
    'Softboll',
    'Speed Badminton',
    'Speedcubing',
    'Speedway',
    'Sportdykning',
    'Sportfiske',
    'Sportskytte',
    'Springskytte',
    'Squash',
    'Streetbasket',
    'Streethockey',
    'Styrkelyft',
    'Bänkpress',
    'Knäböj',
    'Marklyft',
    'Stövelkastning',
    'Sumobrottning',
    'Taekwondo',
    'Teamåkning',
    'Tennis',
    'Tjurfäktning',
    'Traktorpulling',
    'Travsport',
    'Triathlon',
    'Tuppfäktning',
    'Tyngdlyftning',
    'Trampolin', //p4 end
    'Undervattensrugby',
    'Undervattenshockey',
    'Utomhushandboll',
    'Varpa',
    'Vattenpolo',
    'Vattenskidor',
    'Vindsurfing',
    'Volleyboll',
    'Voltige', //p5 end
];
